### ISSUE TITLE
PierianDx Upload to ctTSO with RedCap metadata Feat. Request

### ISSUE THREAD

**Issue by alexiswl** [umccr/data-portal-apis#285]
Upload ctTSO files to PierianDx service along with RedCap metadata.  

Current plan is as follows:

1. Get relative files from ctTSO output dataset to be uploaded to PierianDx in portal
2. Get metadata from redcap in portal
3. Send to AWS Fargate / AWS Batch that will upload ctTSO data to PierianDx

As discussed in the meeting today - 
* Portal will likely house redcap data in its own database (nightly sync etc).  
* Use of dynamodb is an alternative rather than specifying input parameters into AWS BATCH (which can be problematic).  
* How we upload is up to docker image implementation, can use the java cgw uploader, pyriandx or just CURL APIs for now

![image](https://user-images.githubusercontent.com/8197659/132453567-25321d16-d0a2-43b5-b40b-aaec2d23a1e3.png)

**Comment by victorskl** [comment]
**REDCap Tasks:**

- [ ] Explore [PyCAP](https://github.com/redcap-tools/PyCap) -- [supplementary](https://cran.r-project.org/web/packages/REDCapR/vignettes/TroubleshootingApiCalls.html) 
- [ ] Explore [REDCap API](https://redcap.healthinformatics.unimelb.edu.au/api/help/) -- **need account**
- [ ] Import metadata through API from REDCap Test Project -- **need collab with Data Managers**


**PierianDx Tasks:**

- [ ] Explore _RunUploader_ or direct S3 upload with _specified structure_ (_ditto discuss offline/Trello_)
- [ ] Explore whether to use [pyriandx](https://umccr.github.io/pyriandx/user.html#accession-a-new-case) for accessioning a new case + additional case file uploads (e.g. coverage qc text file)
- [ ] _Optionally_ explore PierianDx [Informatics Job Polling](https://umccr.github.io/pyriandx/user.html#polling-job-status) 
  - _optional_ such that this is _set-and-go_ job without needing tracking as User will use CGW UI for Report?
  - _required_ iff we need to [ingest the Report](https://umccr.github.io/pyriandx/user.html#download-analysis-report) back into Portal 


**Portal Tasks:**

- Implement any middleware needs (orchestration) based on ☝️ i.e. if so, incubate under `data_processors` package
- Consider PierianDx case accession metadata capture (so that Portal UI can hint forward link back to CGW UI)

**Comment by andrei-seleznev** [comment]
Practical TODOs here:
1 - Redcap metadata retrieval & storage in DataPortal
	- Set up model to store RedcapMetadata (PatientMetadata? need name for model)
	- Set up (lambda?) to pull RedcapMetadata from Redcap
	- Set up nightly sync
	
Metadata Questions:
What fields are needed for PieranDX?
What fields might be needed for Clarity, when we get to that part?

2 -  PieranDx uploading
	- Docker image needs to be set up for upload, files mounted appropriately
	- AWS Fargate (or Batch?) set up to kick off docker image
	- Docker image handles upload internally  (RunUIploader or direct S3)?
Alexis you're working on first and last points above?

**Comment by alexiswl** [comment]
Re point 2, if we use the aws s3 cp we won't need to mount files in Docker image at all. In fact if we have a presigned url as input (from gds), does anyone know a way of uploading the contents of a url to a file on s3? Could this be done from entirely inside the portal?

**Comment by andrei-seleznev** [comment]
After discussion, will first try to do 'retrieve RedCAP Metadata' without ever saving data in the portal - call lambda (with desired sample names? what params), retrieve & return. If problems or API too slow, will look at storing.

**Comment by alexiswl** [comment]
@andrei-seleznev have managed to get the lambda working with json inputs - see slack thread: https://umccr.slack.com/archives/C025TLC7D/p1637713420269000?thread_ts=1637646645.262300&cid=C025TLC7D

You were well ahead of me on the redcap ingestion, given the inputs for the lambda are clear, can you see if this is going to be a simple link up between the two services via the portal?

**Comment by victorskl** [comment]
Ok folks, let de-scope RedCAP part. In that case, this ticket is good to go/close with [Ragdoll](https://github.com/umccr/infrastructure/milestone/3) release. _(Sorry, I should have checked before finalising release yesterday)_.

Anyhow; here is summary:

- this is now done and continue in its own spin off [cttso-ica-to-pieriandx](https://github.com/umccr/cttso-ica-to-pieriandx/tags) repo
- sub-pipeline `cttso-ica-to-pieriandx` app is released with [this PR](https://github.com/umccr/infrastructure/pull/183) into PROD
- this first-cut implementation delivers just manual trigger of this pipeline

Descope:

- descope RedCAP to next iteration
- we shall explore further automation hook from Portal with RedCAP in next iteration....

Closing....

@alexiswl @andrei-seleznev @reisingerf
